### ISSUE TITLE
Chunk: {r multiple_Selecting_rows_cols}

### ISSUE THREAD

**Issue by jimrothstein** [LucyNjoki/R-LadiesAbuja_Data-Manipulation-with-data.table-in-R#1]
- NOW:

We can do the above simultaneously. For example,      

```{r multiple_Selecting_rows_cols}
# select rows, and creating new cols
penguinsDT[species == "Adelie" & 
             bill_length_mm < 50 &
             body_mass_g > 4500,
             !c("island")]
```

- COMMENT:
I do not see how example shows "creating new cols"
`j` should be: .(island, bill_length = bill_length_mm)

**Comment by LucyNjoki** [comment]
> * NOW:
> 
> We can do the above simultaneously. For example,
> 
> ```
> # select rows, and creating new cols
> penguinsDT[species == "Adelie" & 
>              bill_length_mm < 50 &
>              body_mass_g > 4500,
>              !c("island")]
> ```
> 
> * COMMENT:
>   I do not see how example shows "creating new cols"
>   `j` should be: .(island, bill_length = bill_length_mm)

Indeed yes, it doesn't show creating new columns here. Well, I'll rewrite the comment that shows how one can select rows based on multiple conditions, and drop the `island` column. Thank you!
